INSERT INTO dbo.Country VALUES ('Afghanistan');
INSERT INTO dbo.Country VALUES ('Albania');
INSERT INTO dbo.Country VALUES ('Algeria');
INSERT INTO dbo.Country VALUES ('Andorra');
INSERT INTO dbo.Country VALUES ('Angola');
INSERT INTO dbo.Country VALUES ('Antigua and Barbuda');
INSERT INTO dbo.Country VALUES ('Argentina');
INSERT INTO dbo.Country VALUES ('Armenia');
INSERT INTO dbo.Country VALUES ('Australia');
INSERT INTO dbo.Country VALUES ('Austria');
INSERT INTO dbo.Country VALUES ('Azerbaijan');
INSERT INTO dbo.Country VALUES ('Bahamas');
INSERT INTO dbo.Country VALUES ('Bahrain');
INSERT INTO dbo.Country VALUES ('Bangladesh');
INSERT INTO dbo.Country VALUES ('Barbados');
INSERT INTO dbo.Country VALUES ('Belarus');
INSERT INTO dbo.Country VALUES ('Belgium');
INSERT INTO dbo.Country VALUES ('Belize');
INSERT INTO dbo.Country VALUES ('Benin');
INSERT INTO dbo.Country VALUES ('Bhutan');
INSERT INTO dbo.Country VALUES ('Bolivia');
INSERT INTO dbo.Country VALUES ('Bosnia and Herzegovina');
INSERT INTO dbo.Country VALUES ('Botswana');
INSERT INTO dbo.Country VALUES ('Brazil');
INSERT INTO dbo.Country VALUES ('Brunei');
INSERT INTO dbo.Country VALUES ('Bulgaria');
INSERT INTO dbo.Country VALUES ('Burkina Faso');
INSERT INTO dbo.Country VALUES ('Burundi');
INSERT INTO dbo.Country VALUES ('Côte d''Ivoire');
INSERT INTO dbo.Country VALUES ('Cabo Verde');
INSERT INTO dbo.Country VALUES ('Cambodia');
INSERT INTO dbo.Country VALUES ('Cameroon');
INSERT INTO dbo.Country VALUES ('Canada');
INSERT INTO dbo.Country VALUES ('Central African Republic');
INSERT INTO dbo.Country VALUES ('Chad');
INSERT INTO dbo.Country VALUES ('Chile');
INSERT INTO dbo.Country VALUES ('China');
INSERT INTO dbo.Country VALUES ('Colombia');
INSERT INTO dbo.Country VALUES ('Comoros');
INSERT INTO dbo.Country VALUES ('Congo (Congo-Brazzaville)');
INSERT INTO dbo.Country VALUES ('Costa Rica');
INSERT INTO dbo.Country VALUES ('Croatia');
INSERT INTO dbo.Country VALUES ('Cuba');
INSERT INTO dbo.Country VALUES ('Cyprus');
INSERT INTO dbo.Country VALUES ('Czechia (Czech Republic)');
INSERT INTO dbo.Country VALUES ('Democratic Republic of the Congo');
INSERT INTO dbo.Country VALUES ('Denmark');
INSERT INTO dbo.Country VALUES ('Djibouti');
INSERT INTO dbo.Country VALUES ('Dominica');
INSERT INTO dbo.Country VALUES ('Dominican Republic');
INSERT INTO dbo.Country VALUES ('Ecuador');
INSERT INTO dbo.Country VALUES ('Egypt');
INSERT INTO dbo.Country VALUES ('El Salvador');
INSERT INTO dbo.Country VALUES ('Equatorial Guinea');
INSERT INTO dbo.Country VALUES ('Eritrea');
INSERT INTO dbo.Country VALUES ('Estonia');
INSERT INTO dbo.Country VALUES ('Eswatini');
INSERT INTO dbo.Country VALUES ('Ethiopia');
INSERT INTO dbo.Country VALUES ('Fiji');
INSERT INTO dbo.Country VALUES ('Finland');
INSERT INTO dbo.Country VALUES ('France');
INSERT INTO dbo.Country VALUES ('Gabon');
INSERT INTO dbo.Country VALUES ('Gambia');
INSERT INTO dbo.Country VALUES ('Georgia');
INSERT INTO dbo.Country VALUES ('Germany');
INSERT INTO dbo.Country VALUES ('Ghana');
INSERT INTO dbo.Country VALUES ('Greece');
INSERT INTO dbo.Country VALUES ('Grenada');
INSERT INTO dbo.Country VALUES ('Guatemala');
INSERT INTO dbo.Country VALUES ('Guinea');
INSERT INTO dbo.Country VALUES ('Guinea-Bissau');
INSERT INTO dbo.Country VALUES ('Guyana');
INSERT INTO dbo.Country VALUES ('Haiti');
INSERT INTO dbo.Country VALUES ('Holy See');
INSERT INTO dbo.Country VALUES ('Honduras');
INSERT INTO dbo.Country VALUES ('Hungary');
INSERT INTO dbo.Country VALUES ('Iceland');
INSERT INTO dbo.Country VALUES ('India');
INSERT INTO dbo.Country VALUES ('Indonesia');
INSERT INTO dbo.Country VALUES ('Iran');
INSERT INTO dbo.Country VALUES ('Iraq');
INSERT INTO dbo.Country VALUES ('Ireland');
INSERT INTO dbo.Country VALUES ('Israel');
INSERT INTO dbo.Country VALUES ('Italy');
INSERT INTO dbo.Country VALUES ('Jamaica');
INSERT INTO dbo.Country VALUES ('Japan');
INSERT INTO dbo.Country VALUES ('Jordan');
INSERT INTO dbo.Country VALUES ('Kazakhstan');
INSERT INTO dbo.Country VALUES ('Kenya');
INSERT INTO dbo.Country VALUES ('Kiribati');
INSERT INTO dbo.Country VALUES ('Kuwait');
INSERT INTO dbo.Country VALUES ('Kyrgyzstan');
INSERT INTO dbo.Country VALUES ('Laos');
INSERT INTO dbo.Country VALUES ('Latvia');
INSERT INTO dbo.Country VALUES ('Lebanon');
INSERT INTO dbo.Country VALUES ('Lesotho');
INSERT INTO dbo.Country VALUES ('Liberia');
INSERT INTO dbo.Country VALUES ('Libya');
INSERT INTO dbo.Country VALUES ('Liechtenstein');
INSERT INTO dbo.Country VALUES ('Lithuania');
INSERT INTO dbo.Country VALUES ('Luxembourg');
INSERT INTO dbo.Country VALUES ('Madagascar');
INSERT INTO dbo.Country VALUES ('Malawi');
INSERT INTO dbo.Country VALUES ('Malaysia');
INSERT INTO dbo.Country VALUES ('Maldives');
INSERT INTO dbo.Country VALUES ('Mali');
INSERT INTO dbo.Country VALUES ('Malta');
INSERT INTO dbo.Country VALUES ('Marshall Islands');
INSERT INTO dbo.Country VALUES ('Mauritania');
INSERT INTO dbo.Country VALUES ('Mauritius');
INSERT INTO dbo.Country VALUES ('Mexico');
INSERT INTO dbo.Country VALUES ('Micronesia');
INSERT INTO dbo.Country VALUES ('Moldova');
INSERT INTO dbo.Country VALUES ('Monaco');
INSERT INTO dbo.Country VALUES ('Mongolia');
INSERT INTO dbo.Country VALUES ('Montenegro');
INSERT INTO dbo.Country VALUES ('Morocco');
INSERT INTO dbo.Country VALUES ('Mozambique');
INSERT INTO dbo.Country VALUES ('Myanmar');
INSERT INTO dbo.Country VALUES ('Namibia');
INSERT INTO dbo.Country VALUES ('Nauru');
INSERT INTO dbo.Country VALUES ('Nepal');
INSERT INTO dbo.Country VALUES ('Netherlands');
INSERT INTO dbo.Country VALUES ('New Zealand');
INSERT INTO dbo.Country VALUES ('Nicaragua');
INSERT INTO dbo.Country VALUES ('Niger');
INSERT INTO dbo.Country VALUES ('Nigeria');
INSERT INTO dbo.Country VALUES ('North Korea');
INSERT INTO dbo.Country VALUES ('North Macedonia');
INSERT INTO dbo.Country VALUES ('Norway');
INSERT INTO dbo.Country VALUES ('Oman');
INSERT INTO dbo.Country VALUES ('Pakistan');
INSERT INTO dbo.Country VALUES ('Palau');
INSERT INTO dbo.Country VALUES ('Palestine State');
INSERT INTO dbo.Country VALUES ('Panama');
INSERT INTO dbo.Country VALUES ('Papua New Guinea');
INSERT INTO dbo.Country VALUES ('Paraguay');
INSERT INTO dbo.Country VALUES ('Peru');
INSERT INTO dbo.Country VALUES ('Philippines');
INSERT INTO dbo.Country VALUES ('Poland');
INSERT INTO dbo.Country VALUES ('Portugal');
INSERT INTO dbo.Country VALUES ('Qatar');
INSERT INTO dbo.Country VALUES ('Romania');
INSERT INTO dbo.Country VALUES ('Russia');
INSERT INTO dbo.Country VALUES ('Rwanda');
INSERT INTO dbo.Country VALUES ('Saint Kitts and Nevis');
INSERT INTO dbo.Country VALUES ('Saint Lucia');
INSERT INTO dbo.Country VALUES ('Saint Vincent and the Grenadines');
INSERT INTO dbo.Country VALUES ('Samoa');
INSERT INTO dbo.Country VALUES ('San Marino');
INSERT INTO dbo.Country VALUES ('Sao Tome and Principe');
INSERT INTO dbo.Country VALUES ('Saudi Arabia');
INSERT INTO dbo.Country VALUES ('Senegal');
INSERT INTO dbo.Country VALUES ('Serbia');
INSERT INTO dbo.Country VALUES ('Seychelles');
INSERT INTO dbo.Country VALUES ('Sierra Leone');
INSERT INTO dbo.Country VALUES ('Singapore');
INSERT INTO dbo.Country VALUES ('Slovakia');
INSERT INTO dbo.Country VALUES ('Slovenia');
INSERT INTO dbo.Country VALUES ('Solomon Islands');
INSERT INTO dbo.Country VALUES ('Somalia');
INSERT INTO dbo.Country VALUES ('South Africa');
INSERT INTO dbo.Country VALUES ('South Korea');
INSERT INTO dbo.Country VALUES ('South Sudan');
INSERT INTO dbo.Country VALUES ('Spain');
INSERT INTO dbo.Country VALUES ('Sri Lanka');
INSERT INTO dbo.Country VALUES ('Sudan');
INSERT INTO dbo.Country VALUES ('Suriname');
INSERT INTO dbo.Country VALUES ('Sweden');
INSERT INTO dbo.Country VALUES ('Switzerland');
INSERT INTO dbo.Country VALUES ('Syria');
INSERT INTO dbo.Country VALUES ('Tajikistan');
INSERT INTO dbo.Country VALUES ('Tanzania');
INSERT INTO dbo.Country VALUES ('Thailand');
INSERT INTO dbo.Country VALUES ('Timor-Leste');
INSERT INTO dbo.Country VALUES ('Togo');
INSERT INTO dbo.Country VALUES ('Tonga');
INSERT INTO dbo.Country VALUES ('Trinidad and Tobago');
INSERT INTO dbo.Country VALUES ('Tunisia');
INSERT INTO dbo.Country VALUES ('Turkey');
INSERT INTO dbo.Country VALUES ('Turkmenistan');
INSERT INTO dbo.Country VALUES ('Tuvalu');
INSERT INTO dbo.Country VALUES ('Uganda');
INSERT INTO dbo.Country VALUES ('Ukraine');
INSERT INTO dbo.Country VALUES ('United Arab Emirates');
INSERT INTO dbo.Country VALUES ('United Kingdom');
INSERT INTO dbo.Country VALUES ('United States of America');
INSERT INTO dbo.Country VALUES ('Uruguay');
INSERT INTO dbo.Country VALUES ('Uzbekistan');
INSERT INTO dbo.Country VALUES ('Vanuatu');
INSERT INTO dbo.Country VALUES ('Venezuela');
INSERT INTO dbo.Country VALUES ('Vietnam');
INSERT INTO dbo.Country VALUES ('Yemen');
INSERT INTO dbo.Country VALUES ('Zambia');
INSERT INTO dbo.Country VALUES ('Zimbabwe');
